/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ChessToken__factory } from './ChessToken__factory.js';
export { ChessWager__factory } from './ChessWager__factory.js';