/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ChessWagerInterface extends Interface {
    getFunction(nameOrSignature: "cancelMatch" | "chessToken" | "createMatch" | "joinMatch" | "matches" | "nextMatchId" | "owner" | "renounceOwnership" | "resolveDraw" | "resolveMatch" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MatchCancelled" | "MatchCreated" | "MatchDrawn" | "MatchJoined" | "MatchResolved" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelMatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'chessToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'createMatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'joinMatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'matches', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextMatchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveMatch', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'cancelMatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chessToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinMatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextMatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace MatchCancelledEvent {
      export type InputTuple = [matchId: BigNumberish, player1: AddressLike];
      export type OutputTuple = [matchId: bigint, player1: string];
      export interface OutputObject {matchId: bigint, player1: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MatchCreatedEvent {
      export type InputTuple = [matchId: BigNumberish, player1: AddressLike, wagerAmount: BigNumberish];
      export type OutputTuple = [matchId: bigint, player1: string, wagerAmount: bigint];
      export interface OutputObject {matchId: bigint, player1: string, wagerAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MatchDrawnEvent {
      export type InputTuple = [matchId: BigNumberish, splitAmount: BigNumberish];
      export type OutputTuple = [matchId: bigint, splitAmount: bigint];
      export interface OutputObject {matchId: bigint, splitAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MatchJoinedEvent {
      export type InputTuple = [matchId: BigNumberish, player2: AddressLike];
      export type OutputTuple = [matchId: bigint, player2: string];
      export interface OutputObject {matchId: bigint, player2: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MatchResolvedEvent {
      export type InputTuple = [matchId: BigNumberish, winner: AddressLike, payout: BigNumberish];
      export type OutputTuple = [matchId: bigint, winner: string, payout: bigint];
      export interface OutputObject {matchId: bigint, winner: string, payout: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ChessWager extends BaseContract {
    
    connect(runner?: ContractRunner | null): ChessWager;
    waitForDeployment(): Promise<this>;

    interface: ChessWagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelMatch: TypedContractMethod<
      [matchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    chessToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createMatch: TypedContractMethod<
      [wagerAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    joinMatch: TypedContractMethod<
      [matchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    matches: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, string] & {player1: string, player2: string, wagerAmount: bigint, state: bigint, winner: string }],
      'view'
    >
    

    
    nextMatchId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDraw: TypedContractMethod<
      [matchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveMatch: TypedContractMethod<
      [matchId: BigNumberish, winner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelMatch'): TypedContractMethod<
      [matchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'chessToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createMatch'): TypedContractMethod<
      [wagerAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'joinMatch'): TypedContractMethod<
      [matchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'matches'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, string] & {player1: string, player2: string, wagerAmount: bigint, state: bigint, winner: string }],
      'view'
    >;
getFunction(nameOrSignature: 'nextMatchId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDraw'): TypedContractMethod<
      [matchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveMatch'): TypedContractMethod<
      [matchId: BigNumberish, winner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MatchCancelled'): TypedContractEvent<MatchCancelledEvent.InputTuple, MatchCancelledEvent.OutputTuple, MatchCancelledEvent.OutputObject>;
getEvent(key: 'MatchCreated'): TypedContractEvent<MatchCreatedEvent.InputTuple, MatchCreatedEvent.OutputTuple, MatchCreatedEvent.OutputObject>;
getEvent(key: 'MatchDrawn'): TypedContractEvent<MatchDrawnEvent.InputTuple, MatchDrawnEvent.OutputTuple, MatchDrawnEvent.OutputObject>;
getEvent(key: 'MatchJoined'): TypedContractEvent<MatchJoinedEvent.InputTuple, MatchJoinedEvent.OutputTuple, MatchJoinedEvent.OutputObject>;
getEvent(key: 'MatchResolved'): TypedContractEvent<MatchResolvedEvent.InputTuple, MatchResolvedEvent.OutputTuple, MatchResolvedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'MatchCancelled(uint256,address)': TypedContractEvent<MatchCancelledEvent.InputTuple, MatchCancelledEvent.OutputTuple, MatchCancelledEvent.OutputObject>;
      MatchCancelled: TypedContractEvent<MatchCancelledEvent.InputTuple, MatchCancelledEvent.OutputTuple, MatchCancelledEvent.OutputObject>;
    

      'MatchCreated(uint256,address,uint256)': TypedContractEvent<MatchCreatedEvent.InputTuple, MatchCreatedEvent.OutputTuple, MatchCreatedEvent.OutputObject>;
      MatchCreated: TypedContractEvent<MatchCreatedEvent.InputTuple, MatchCreatedEvent.OutputTuple, MatchCreatedEvent.OutputObject>;
    

      'MatchDrawn(uint256,uint256)': TypedContractEvent<MatchDrawnEvent.InputTuple, MatchDrawnEvent.OutputTuple, MatchDrawnEvent.OutputObject>;
      MatchDrawn: TypedContractEvent<MatchDrawnEvent.InputTuple, MatchDrawnEvent.OutputTuple, MatchDrawnEvent.OutputObject>;
    

      'MatchJoined(uint256,address)': TypedContractEvent<MatchJoinedEvent.InputTuple, MatchJoinedEvent.OutputTuple, MatchJoinedEvent.OutputObject>;
      MatchJoined: TypedContractEvent<MatchJoinedEvent.InputTuple, MatchJoinedEvent.OutputTuple, MatchJoinedEvent.OutputObject>;
    

      'MatchResolved(uint256,address,uint256)': TypedContractEvent<MatchResolvedEvent.InputTuple, MatchResolvedEvent.OutputTuple, MatchResolvedEvent.OutputObject>;
      MatchResolved: TypedContractEvent<MatchResolvedEvent.InputTuple, MatchResolvedEvent.OutputTuple, MatchResolvedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }